### PR TITLE
Send the X-JFrog-Art-Api instead of using basic auth

### PR DESCRIPTION
**Pull request by kihehs**
Using this header means we don't have to send the username anymore. I believe this means we can remove usernames completely.

### CODE REVIEW

**Comment by mara214** [comment]
Hi @kihehs, is this strictly backwards compatible / tested that it doesn't break anything? 😊 

Also a good follow up would be to remove the username from the `Credentials` file

**Comment by kihehs** [comment]
I can't test publishing and downloading right now, but it would appear that the tests are green, for what it's worth :)

**Comment by kihehs** [comment]
Okay, now I know that downloading works, so presumably publishing does as well :)

**Comment by mara214** [comment]
The docs should be updated before we can merge, but other than that it lgtm!

https://github.com/helsing-ai/buffrs/blob/main/docs/src/getting-started/installation.md

**Comment by kihehs** [comment]
Alright, I removed the username line, and did a cursory search. I think it's finally gone :)

**Review by mara214 — APPROVED** [review]

**Pull request merged**
